# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd ; rpm/helpers/add_new_device.sh
Description: Pattern with packages for hammerhead configurations
Name: jolla-configuration-hammerhead
Requires:
- pattern:jolla-hw-adaptation-hammerhead
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration hammerhead

